### ISSUE TITLE
genisoimage not available on some systems

### ISSUE THREAD

**Issue by zdykstra** [virt-lightning/virt-lightning#139]
I'm running virt-lightning on Void Linux, which does not package *genisoimage*. It does package *makeisofs* which seems to be fully compatible with the arguments passed to *genisoimage*.  I can just duplicate the solution used to find the KVM binary, unless you'd like this as a configuration option.

**Comment by goneri** [comment]
Thanks for the bug report. Well, yes, I guess we can go with the auto-discovery.

**Comment by zdykstra** [comment]
Added in #142
