### ISSUE TITLE
Add support for forwarded SSH key

### ISSUE THREAD

**Issue by BubaVV** [virt-lightning/virt-lightning#224]
I think that support of public keys extracted from `ssh-add -L` output would be nice. It will help a bit to run vl on some cloud VM accessed via `ssh -A user@vm` command. Currently, i need to copy `id_rsa.pub` from localhost to VM. Also, unrelated, but somewhat related issue: `ssh_key_file` config option is not documented yet

**Comment by goneri** [comment]
Hi @BubaVV, would you like to push a PR to document the `ssh_key_file` option?

Regarding the copy of the public SSh key, I'm not totally sure how to implement what you describe. I think this is the kind of thing I would prefer to do after the deployment with an Ansible playbook, or a `scp` call in a shell script. We can also expose a configuration key that allow the user to set the `bootcmd` or `runcmd`, see: https://cloudinit.readthedocs.io/en/latest/topics/examples.html

**Comment by goneri** [comment]
I reopen because the issue has been partially addressed.
