### ISSUE TITLE
pip 21.3 fails to resolve test requirements

### ISSUE THREAD

**Issue by BubaVV** [virt-lightning/virt-lightning#226]
Pip uses new dependency resolver since 20.3. It fixes some nasty bugs, but works very slow with unpinned dependencies. It affects tox testing - env build lasts at least tens of minutes
Steps to reproduce:
1. Create virtualenv and activate it. Python >3.6 is good
2. Update pip: `pip install -U pip`. Ensure that pip -V returns value greater then 20.3
3. `pip install -r test-requirements.txt`
It will run for some very long times trying to resolve all dependencies

Possible solution: pin exact versions of flake8 packages in test-requirements.txt

**Comment by BubaVV** [comment]
Update: `cat test-requirements.txt | xargs pip install` works fine

**Comment by BubaVV** [comment]
Proposed a PR https://github.com/virt-lightning/virt-lightning/pull/227

**Comment by goneri** [comment]
Closed by https://github.com/virt-lightning/virt-lightning/pull/227, thanks @BubaVV
