### ISSUE TITLE
Add delete function

### ISSUE THREAD

**Issue by jpic** [virt-lightning/virt-lightning#229]
Since we can start VMs with `vl start`, it would be nice to also delete them with `vl delete`, I'm also interested in the `api.delete()` function.

Would you like to see a patch? That's what I currently have, it comes from the `api.down()` function:

```py
from virt_lightning import api as vl

def vm_delete(name):
    conn = vl._connect_libvirt(vlconf.libvirt_uri)
    hv = vl.vl.LibvirtHypervisor(conn)
    hv.init_network(vlconf.network_name, vlconf.network_cidr)
    hv.init_storage_pool(vlconf.storage_pool)
    for domain in hv.list_domains():
        if domain.name == name:
            hv.clean_up(domain)
    return 'deleted'
```

**Comment by goneri** [comment]
Hi @jpic!

`stop` already clean the resources and I know this confuse people. Maybe we can change that and have:
- `vl stop foo` to turn off the VM
- `vl delete foo` to clean up the VM (and possibly stop it too)

Feel free to submit a patch, I will be happy to review it.

**Comment by jpic** [comment]
Thanks for the heads up! In the mean time I added more documentation in CLI in #230

I find it a bit sad that the CLI does not autogenerate better documentation based on docstrings, ie. it could generate the list of commands as help based on the docstring, like [cli2](https://cli2.rtfd.io)
