### ISSUE TITLE
Snapshots / restore?

### ISSUE THREAD

**Issue by jpic** [virt-lightning/virt-lightning#235]
Hi!

Maybe it would be interresting to be able to create our own boxes from VMs like vCenter does, except we do it via Python API / CLI.

What do you think?

**Comment by goneri** [comment]
Hi @jpic,

Snapshot/restore is a good idea and libvirt provides an API for that. Yes, it would be great to be able to snapshot a VM. Regarding the vCenter comparaison, you can indeed build your own images, it should just work.

**Comment by BubaVV** [comment]
Snapshots are supported in master branch and next release (2.4.0, probably)
