### ISSUE TITLE
Allow specifiying the video model

### ISSUE THREAD

**Issue by ooraini** [virt-lightning/virt-lightning#237]
I'm running CentOS 9 Stream locally, and I'm unable to run `vl up` due to an issue with the `qxl` video model.

```
❯ vl up
⚡ centos-9-stream 
Traceback (most recent call last):
  File "/home/ooraini/.local/bin/vl", line 8, in <module>
    sys.exit(main())
  File "/home/ooraini/.local/lib/python3.9/site-packages/virt_lightning/shell.py", line 362, in main
    action_func(configuration=configuration, **vars(args))
  File "/home/ooraini/.local/lib/python3.9/site-packages/virt_lightning/api.py", line 206, in up
    loop.run_until_complete(deploy())
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ooraini/.local/lib/python3.9/site-packages/virt_lightning/api.py", line 198, in deploy
    await f
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ooraini/.local/lib/python3.9/site-packages/virt_lightning/api.py", line 122, in _start_domain
    domain = hv.create_domain(name=host["name"], distro=distro)
  File "/home/ooraini/.local/lib/python3.9/site-packages/virt_lightning/virt_lightning.py", line 111, in create_domain
    dom = self.conn.defineXML(ET.tostring(root).decode())
  File "/usr/lib64/python3.9/site-packages/libvirt.py", line 4414, in defineXML
    raise libvirtError('virDomainDefineXML() failed')
libvirt.libvirtError: unsupported configuration: domain configuration does not support video model 'qxl'
```

I think the [issue](https://bugzilla.redhat.com/show_bug.cgi?id=1869216) is with the unavailable package `qemu-ui-gtk`. Is there any specific requirement for `qxl`?

The following lines are relevant:
* [https://github.com/virt-lightning/virt-lightning/blob/a6e40ceeebd66c23ad7dd177b5d9281bf474a415/virt_lightning/templates.py#L89](https://github.com/virt-lightning/virt-lightning/blob/a6e40ceeebd66c23ad7dd177b5d9281bf474a415/virt_lightning/templates.py#L89)
* [https://github.com/virt-lightning/virt-lightning/blob/78718b408b14dcdb6ac727942548318e112a33b3/virt_lightning/virt_lightning.py#L110](https://github.com/virt-lightning/virt-lightning/blob/78718b408b14dcdb6ac727942548318e112a33b3/virt_lightning/virt_lightning.py#L110)

**Comment by ooraini** [comment]
I was able to get things working with the following template:
```
DOMAIN_VNC_XML = """
<domain type='kvm'>
  <name></name>
  <memory unit='KiB'>786432</memory>
  <currentMemory unit='KiB'>786432</currentMemory>
  <vcpu>2</vcpu>
  <os>
    <type arch='x86_64' machine='pc'>hvm</type>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <vmport state='off'/>
  </features>
  <cpu mode='host-model' check='partial'>
    <model fallback='allow'/>
  </cpu>
  <clock offset='utc'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <pm>
    <suspend-to-mem enabled='no'/>
    <suspend-to-disk enabled='no'/>
  </pm>
  <devices>
    <emulator>/usr/bin/qemu-kvm</emulator>
    <controller type='usb' index='0' model='ich9-ehci1'></controller>
    <controller type='pci' index='0' model='pci-root'/>
    <console type='pty'>
      <target type='serial'/>
    </console>
    <console type='pty'>
      <target type='virtio'/>
    </console>
    <channel type='unix'>
      <target type='virtio' name='org.qemu.guest_agent.0' state='connected'/>
    </channel>
    <input type='mouse' bus='ps2'/>
    <input type='keyboard' bus='ps2'/>
    <graphics type="vnc" port="-1" autoport="yes" listen="127.0.0.1" keymap="en-us">
      <listen type="address" address="127.0.0.1"/>
    </graphics>
    <audio id="1" type="none"/>
    <video>
      <model type="virtio" heads="1" primary="yes">
        <acceleration accel3d="no"/>
      </model>
    </video>
    <memballoon model='virtio'></memballoon>
  </devices>
</domain>
"""  # NOQA
```

After looking at libvirt documentation, I removed `<address>`  elements and it's working fine.

**Comment by goneri** [comment]
Thank you for the bug report. I'm surprised qxl is not supported.

According to https://libvirt.org/formatdomain.html#video-devices

`The video element is the container for describing video devices. For backwards compatibility, if no video is set but there is a graphics in domain xml, then libvirt will add a default video according to the guest type.`

So maybe it's even better to just drop the `<video />` section and let Libvirt handle it.

**Comment by ooraini** [comment]
@goneri 
I removed the video section and indeed a default one was added:
```
    <video>
      <model type="cirrus" vram="16384" heads="1" primary="yes"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x0"/>
    </video>
```

Please note that I had to also change the `<graphics>` section to VNC. The spice-server package is no longer included in Stream 9, and for that matter RHEL 9.

We can also make the template string itself configurable and that way the user can supply their own custom XML.

**Comment by goneri** [comment]
> @goneri I removed the video section and indeed a default one was added:
> 
> ```
>     <video>
>       <model type="cirrus" vram="16384" heads="1" primary="yes"/>
>       <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x0"/>
>     </video>
> ```
> 
> Please note that I had to also change the `<graphics>` section to VNC. The spice-server package is no longer included in Stream 9, and for that matter RHEL 9.

I would suggest to:

- default on VNC, it should work well enough for everybody.
- add a configuration key to pass a different driver.

> We can also make the template string itself configurable and that way the user can supply their own custom XML.

Yes, it's a good idea.

Would you like to submit a patch for one of these features?

**Comment by ooraini** [comment]
To summarize:

- VNC for graphics section.
- No video section(Defaulted by libvirt)
- Two consoles, emulated and accelerated
- QEMU agent connection channel.
- Configurable XML snippets.

**Comment by goneri** [comment]
Can we close the issue now?

**Comment by ooraini** [comment]
I did try to work on configurable XML snippet, but I faced some issues on the way I propagated the configuration across all classes. I ended up with a lot of changes and not-so clean code. I will close this for now.
