### ISSUE TITLE
New release on pypi

### ISSUE THREAD

**Issue by ooraini** [virt-lightning/virt-lightning#249]
There haven't been a new release on pypi for a while.

I'm reading:
[https://packaging.python.org/en/latest/tutorials/packaging-projects/](https://packaging.python.org/en/latest/tutorials/packaging-projects/)

Perhaps we can publish them as part of a Github workflow? Or upload them to Github pages with each successful test run(every commit)?

**Comment by goneri** [comment]
Hi @ooraini,

You're totally right. We're due for a new minor release. I can push an upload, but first we need to refresh the `changelog.md` with a new 2.2.0 entry that list the recent changes. Would you like to do it?

I like the Github workflow idea. Is this something you're familiar with? We can try something like that for the next release.
