### ISSUE TITLE
pip3 install --user virt-lightning error: externally-managed-environment Debian-12

### ISSUE THREAD

**Issue by jerzerisz** [virt-lightning/virt-lightning#281]
root@vl-test:~/.local/bin# pip3 install --user --no-deps virt-lightning
error: externally-managed-environment

should recommended/documented fix be --break-system-packages or pipx?

**Comment by goneri** [comment]
You should not use `pip` as root user.

**Comment by goneri** [comment]
Yes `pipx` maybe a better option indeed. Thank you for investigating that!
