### ISSUE TITLE
How do I add my own images ? or better yet can we get debian-13 on the list ?

### ISSUE THREAD

**Issue by rprihoda** [virt-lightning/virt-lightning#290]
Is there a way to create and use my own images? Also, can we get debian trixie added ?

**Comment by goneri** [comment]
Hi @rprihoda!

You can use an existing cloud-ready image from https://cloud.debian.org/images/cloud/ and specialize it with guestfs/virt-customize.
I just found this example: https://wiki.debian.org/ThomasChung/CloudImage

Once your image is ready, just copy it in `/var/lib/virt-lightning/pool/upstream/`, you can add a YAML file aside if you want to pass some specific configuration for that image. Eg:

```
$ ls /var/lib/virt-lightning/pool/upstream/openbsd-7.1.*
/var/lib/virt-lightning/pool/upstream/openbsd-7.1.qcow2  /var/lib/virt-lightning/pool/upstream/openbsd-7.1.yaml
$ cat /var/lib/virt-lightning/pool/upstream/openbsd-7.1.yaml
python_interpreter: /usr/local/bin/python3
```

**Comment by goneri** [comment]
Also, if you want to add Debian 13 in the list of supported distro (this would be awesome!), you can open up a PR like this one https://github.com/virt-lightning/virt-lightning/pull/286

**Comment by rprihoda** [comment]
Thanks if I get some time , I'll make a PR.
