### ISSUE TITLE
Please, change centos-N-stream to cenetos-stream-N

### ISSUE THREAD

**Issue by renich** [virt-lightning/virt-lightning#304]
Hello,

The official name of CentOS is CentOS Stream now. The version comes after.

**Comment by goneri** [comment]
Hi @renich,

Thank you for the information. Would you like to prepare a PR to fix that?

We need to adjust https://github.com/virt-lightning/virt-lightning/blob/main/virt-lightning.org/www/images/index.md and to add extra lines here https://github.com/virt-lightning/virt-lightning/blob/main/virt-lightning.org/etc/caddy/conf.d/virt-lightning.org.conf#L30-L34 to accept the new names.
